# Generated by Django 3.1.1 on 2020-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20201020_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('P', 'Pantalon'), ('C', 'chemise'), ('J', 'jupe'), ('E', 'ensemble')], default='cosmetic', max_length=30)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='slug-holder')),
                ('selection', models.BooleanField()),
                ('quantity', models.IntegerField(default=1)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('P', 'Pantalon'), ('C', 'chemise'), ('J', 'jupe'), ('E', 'ensemble')], max_length=30),
        ),
    ]
