# Generated by Django 3.1.1 on 2020-11-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20201122_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
