# Generated by Django 3.1.1 on 2020-11-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='url',
            field=models.CharField(max_length=160),
        ),
    ]
