# Generated by Django 3.1.1 on 2020-11-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201116_1553'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_b', models.CharField(max_length=100)),
                ('last_name_b', models.CharField(max_length=100)),
                ('telephone_b', models.CharField(max_length=100)),
                ('company_b', models.CharField(max_length=100)),
                ('country_b', models.CharField(max_length=100)),
                ('address_b', models.CharField(max_length=100)),
                ('street_b', models.CharField(max_length=100)),
                ('city_b', models.CharField(max_length=100)),
                ('region_b', models.CharField(max_length=100)),
                ('zip_b', models.CharField(max_length=100)),
                ('fax_b', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('billing_infos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='checkout.billing')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_c', models.CharField(max_length=40)),
                ('last_name_c', models.CharField(max_length=40)),
                ('phone_c', models.CharField(max_length=40)),
                ('email_c', models.CharField(max_length=40)),
                ('address_c', models.CharField(max_length=100)),
                ('street_c', models.CharField(max_length=100)),
                ('city_c', models.CharField(max_length=100)),
                ('region_c', models.CharField(max_length=100)),
                ('zip_c', models.CharField(max_length=100)),
                ('fax_c', models.CharField(max_length=100)),
                ('session_key_c', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('same_billing_address', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CheckoutDetails',
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='checkout.customer'),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order'),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='checkout.paymentmethod'),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='shiping_infos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='checkout.shipping'),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='checkout.shippingmethod'),
        ),
    ]
