# Generated by Django 3.1.1 on 2020-11-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201116_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutmodel',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checkoutmodel',
            name='shipping_method',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
    ]
