# Generated by Django 3.1.1 on 2020-11-20 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20201116_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutmodel',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='checkoutmodel',
            name='ordered',
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='checkout_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
