# Generated by Django 3.1.1 on 2020-11-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201116_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorder',
            options={'ordering': ['-id']},
        ),
    ]
