# Generated by Django 3.1.1 on 2020-11-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201120_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
